version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    # Disable version updates (only security updates)
    open-pull-requests-limit: 0

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
