# Pull base image
FROM python:3.13-slim-bookworm

# Set environment variables -- see also `app/config/.env.example`
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
  PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN python -m pip install \
  --no-cache-dir --root-user-action=ignore \
  --require-hashes --no-deps \
  -r requirements.txt


## FLY.IO DEPLOYMENT

COPY app .
EXPOSE 8000

# Run migrations and server with entrypoint (SQLite Volume Fly.io)
COPY ./_docker/entrypoint-flyio.sh ./entrypoint.sh
ENTRYPOINT ["sh", "./entrypoint.sh"]
