# Pull base image
FROM python:3.12-slim-bullseye

# Install SQLite
RUN apt-get update && \
  apt-get install -y sqlite3 libsqlite3-dev && \
  rm -rf /var/lib/apt/lists/*

# Set environment variables -- see also `app/config/.env.example`
ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements-dev.txt .
RUN python -m pip install \
  --disable-pip-version-check --no-cache-dir --root-user-action=ignore \
  --require-hashes --no-deps \
  -r requirements-dev.txt
